# netlify.toml
[build]
command = "npm run build"
publish = ".next"

# Optional but recommended
[functions]
node_bundler = "esbuild"

# Use Netlify’s official Next.js runtime (auto-installs)
[[plugins]]
package = "@netlify/plugin-nextjs"
